### ISSUE TITLE
Research migration way

### ISSUE THREAD

**Issue by chandr-andr** [qaspen-python/qaspen#2]
Need to investigate the best way of migrations.  
Migration is a class? Migration has only two functions (apply and rollback operations)?
We need to have the ability to add pre/post-create hooks for migrations (even change the content of the migration file).
As a result of this issue must be text with ideas.

**Comment by reqww** [comment]
So, here's how we can implemet migrations (pretty simple for the begining)
We have to make some kind of DDL
Like AlterTable, AddNull, AddIndex, DropIndex e.t.c.

Those should be classes and we hardcode sql command there like: 
```
class AlterColumnDDL:
    template: str = "ALTER TABLE '{table_name}' ALTER COLUMN '{column}' TYPE {datatype}{using}"
...
```

**Comment by chandr-andr** [comment]
I wanna discuss fields in the migration class.
I think they must have at least a flag of transaction. Because some migrations can't be executed in transactions, for example, concurrent index creation.

@reqww Could you, please, think about migration class fields?

**Comment by theyashl** [comment]
https://alembic.sqlalchemy.org/en/latest/tutorial.html#create-a-migration-script maybe this will help to add some insights?

**Comment by chandr-andr** [comment]
@theyashl 
> [alembic.sqlalchemy.org/en/latest/tutorial.html#create-a-migration-script](https://alembic.sqlalchemy.org/en/latest/tutorial.html#create-a-migration-script) maybe this will help to add some insights?

Hello! Thanks for the link. Ofc we know about the alembic, but we are trying to accumulate all experience of existing migration tools (alembic, django migrations, piccolo migrations, etc.), add changes from our experience, and create totally better new tool.
